### ISSUE TITLE
Template updates are ignored

### ISSUE THREAD

**Issue by hirnschmalz** [1drop/pootle#2]
I created a new project for a TYPO3 extension.
If the template files are updated, the updates are not reflected in the Pootle frontend.

I opened the template file on the filesystem. This file seems to be OK, the latest changes are visibile.

**Comment by htuscher** [comment]
I'm currently working on this issue. Pootle 2.7 removed the command update_against_templates and I must refactor the shell scripts to do this locally with pot2po.
Will be solved approx today.

**Comment by hirnschmalz** [comment]
@hhoechtl Oh - great news! Thanks in advance 👍
